/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.grupogedai.view;

import br.com.grupogedai.model.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author suporte.richardson
 */
public class CadastroDeClientes extends javax.swing.JFrame {

    private Cliente objCliente;

    /**
     * Creates new form CadastroDeClientes
     */
    public CadastroDeClientes() {
        initComponents();

        this.objCliente = new Cliente();

        /*jDesktopPaneDadosCliente.setVisible(false);*/
        jInternalFrameDadosCliente.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelAcoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonLogarCliente = new javax.swing.JButton();
        jDesktopPaneDadosCliente = new javax.swing.JDesktopPane();
        jInternalFrameDadosCliente = new javax.swing.JInternalFrame();
        jPanelInternoDadosCliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Clientes");

        jPanelPrincipal.setLayout(null);

        jPanelAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jLabel1.setText("Cliente Logado:");

        jTextFieldNomeCliente.setEditable(false);
        jTextFieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeClienteActionPerformed(evt);
            }
        });

        jButton1.setText("Visualizar Informações");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonLogarCliente.setText("Logar Cliente");
        jButtonLogarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcoesLayout = new javax.swing.GroupLayout(jPanelAcoes);
        jPanelAcoes.setLayout(jPanelAcoesLayout);
        jPanelAcoesLayout.setHorizontalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAcoesLayout.createSequentialGroup()
                        .addComponent(jButtonLogarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanelAcoesLayout.setVerticalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonLogarCliente))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelAcoes);
        jPanelAcoes.setBounds(20, 30, 560, 120);

        jDesktopPaneDadosCliente.setBackground(new java.awt.Color(240, 240, 240));

        jInternalFrameDadosCliente.setVisible(true);

        jPanelInternoDadosCliente.setLayout(null);

        jLabel2.setText("Nome :");
        jPanelInternoDadosCliente.add(jLabel2);
        jLabel2.setBounds(10, 20, 80, 14);

        jLabel3.setText("Sobrenome :");
        jPanelInternoDadosCliente.add(jLabel3);
        jLabel3.setBounds(10, 50, 80, 14);

        jLabel4.setText("Sexo :");
        jPanelInternoDadosCliente.add(jLabel4);
        jLabel4.setBounds(10, 80, 80, 14);

        jLabel5.setText("Idade :");
        jPanelInternoDadosCliente.add(jLabel5);
        jLabel5.setBounds(10, 110, 80, 14);
        jPanelInternoDadosCliente.add(jTextFieldIdade);
        jTextFieldIdade.setBounds(120, 110, 100, 20);
        jPanelInternoDadosCliente.add(jTextFieldNome);
        jTextFieldNome.setBounds(120, 20, 280, 20);
        jPanelInternoDadosCliente.add(jTextFieldSobrenome);
        jTextFieldSobrenome.setBounds(120, 50, 280, 20);

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jPanelInternoDadosCliente.add(jComboBoxSexo);
        jComboBoxSexo.setBounds(120, 80, 100, 20);

        jButton2.setText("Carregar Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelInternoDadosCliente.add(jButton2);
        jButton2.setBounds(120, 150, 150, 23);

        javax.swing.GroupLayout jInternalFrameDadosClienteLayout = new javax.swing.GroupLayout(jInternalFrameDadosCliente.getContentPane());
        jInternalFrameDadosCliente.getContentPane().setLayout(jInternalFrameDadosClienteLayout);
        jInternalFrameDadosClienteLayout.setHorizontalGroup(
            jInternalFrameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInternoDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        jInternalFrameDadosClienteLayout.setVerticalGroup(
            jInternalFrameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInternoDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDesktopPaneDadosCliente.setLayer(jInternalFrameDadosCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneDadosClienteLayout = new javax.swing.GroupLayout(jDesktopPaneDadosCliente);
        jDesktopPaneDadosCliente.setLayout(jDesktopPaneDadosClienteLayout);
        jDesktopPaneDadosClienteLayout.setHorizontalGroup(
            jDesktopPaneDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jDesktopPaneDadosClienteLayout.setVerticalGroup(
            jDesktopPaneDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneDadosClienteLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jInternalFrameDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jDesktopPaneDadosCliente);
        jDesktopPaneDadosCliente.setBounds(-10, -10, 590, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(600, 481));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Informações do Cliente: \n\n"
                + "Nome: " + this.objCliente.getNome() + "\n"
                + "Sobrenome: " + this.objCliente.getSobrenome() + "\n"
                + "Sexo: " + this.objCliente.getSexo() + "\n"
                + "Idade: " + this.objCliente.getIdade());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonLogarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogarClienteActionPerformed
        jPanelAcoes.setVisible(false);
        jInternalFrameDadosCliente.setVisible(true);
    }//GEN-LAST:event_jButtonLogarClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            getObjCliente().setNome(jTextFieldNome.getText());
            getObjCliente().setSobrenome(jTextFieldSobrenome.getText());
            getObjCliente().setSexo(jComboBoxSexo.getSelectedItem().toString());
            getObjCliente().setIdade(Integer.parseInt(jTextFieldIdade.getText()));

        } catch (NumberFormatException numberEx) {
            objCliente.setIdade(0);
            numberEx.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado ! \n\n"
                    + "Erro: " + e.getMessage());
        }
        
        jDesktopPaneDadosCliente.setVisible(false);
        jInternalFrameDadosCliente.setVisible(false);
        jPanelAcoes.setVisible(true);
        jTextFieldNomeCliente.setText(getObjCliente().getNome() + " " +objCliente.getSobrenome());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonLogarCliente;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JDesktopPane jDesktopPaneDadosCliente;
    private javax.swing.JInternalFrame jInternalFrameDadosCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelAcoes;
    private javax.swing.JPanel jPanelInternoDadosCliente;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldSobrenome;
    // End of variables declaration//GEN-END:variables

    public Cliente getObjCliente() {
        return objCliente;
    }

    public void setObjCliente(Cliente objCliente) {
        this.objCliente = objCliente;
    }

}
